name: curl_converter
description: A Dart package for effortless conversion between cURL commands and Dart class.
version: 1.0.4
repository: https://github.com/utopicnarwhal/curl_converter

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ">=2.3.1 <3.0.0"
  equatable: ^2.0.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  shlex: ^2.0.2


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
